apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongo-mongo-pacman-sddi
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/user-workload@sha256:830d453ecdd43266ba20332c6d63d83b87bc6cc417a6b448c5b31abd081d9e24
        name: container-image
        resources: {}
status: {}
