apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongo-mongo-pacman-sddi
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/user-workload:NA_QT-mongo-mongo-pacman-sddi
        name: container-image
        resources: {}
status: {}
