apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-mongo-pacman-zj14
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-mongo-pacman-zj14
    app.kubernetes.io/part-of: pacman
  name: frontend-mongo-pacman-zj14
  namespace: user1-tenant
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: frontend-mongo-pacman-zj14
    weight: null
status: {}
